---
title: "p8106_mtp"
author: "Abhishek Ajay"
date: "April 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(ISLR)
library(glmnet)
library(caret)
library(corrplot)
library(plotmo)
```

```{r}
library(readr)

day = read.csv("day.csv")
head(day)

x = day %>% 
  select(-dteday) 
x = model.matrix(casual+registered+ cnt~., x)
corrplot(cor(x))
```

According to the above correlation plot, we decided to drop-- instant and intercept.

```{r}
day = day %>% 
  janitor::clean_names() %>% 
  mutate(season = as.factor(season), 
         yr = as.factor(yr), 
         mnth = as.factor(mnth), 
         holiday = as.factor(holiday), 
         weekday = as.factor(weekday), 
         workingday = as.factor(workingday),
         dteday = as.vector(dteday)
         ) %>% 
  select(-c(instant,dteday))
```

```{r}
x_1 = 
  day %>% 
  select(-c( casual, registered, cnt))

x_1 = model.matrix(~., x_1)
y = day$cnt
ridge.mod <-glmnet(x_1, y, alpha=0, lambda =exp(seq(-1, 10, length=100)))
ridge.mod$lambda

dim(coef(ridge.mod))

```

we dropped the dteday because it does is a factor variable with too many levels and it basically is the same as the index which does not tells us anything in this test. 


```{r}
set.seed(2)
cv.ridge <-cv.glmnet(x_1, y,alpha = 0,lambda =exp(seq(-1, 10, length=100)),type.measure = "mse")
plot(cv.ridge)

plot_glmnet(ridge.mod, xvar = "rlambda")

best.lambda = cv.ridge$lambda.min
best.lambda
predict(ridge.mod, s = best.lambda, type="coefficients")
```


```{r}

cv.lasso <-cv.glmnet(x_1, y,alpha = 1,lambda =exp(seq(-1, 10, length=100)),type.measure = "mse")
cv.lasso$lambda.min
plot(cv.lasso)

```

