---
title: "Data Science II Midterm Report"
author: "Pengxuan Chen(pc2853), Abhishek Ajay (aa4266)"
date: "April 7, 2019"
output: pdf_document:
  number_sections: true
  fig_width: 7
  fig_height: 6
  fig_caption: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

dataset & variables introduction

## Data Cleaning



## Github Site
https://github.com/abhishekajay1718/p8106_mtp_group12

# Exploratory Data Analysis/ Visualization

## Predictors Intercorrelation
## Scatterplots
## splines

# Models

The Predictors we kept to predict the outcome `cnt`--- daily count of rental bikes, are season, years, months, holiday, weekday, workingday, weathersituation,  temp, atemp, humidity, and windspeed. We are keeping all the predictors since none of them appears to be redundent to us. We will assume that every parameter we kept will have an impact on the outcome variable before modeling. 

we attempt to fit 5 models in total to this dataset which are simple linear regression, GAM, MARS, ridge, lasso.

## Linear Models


## Non-Linear Models
## Tuning Parameters
## Goodness of Fit
## Estimates
# Limitations

# Conclusion